name: 'remitano_dwh'
version: '1.0.0'

profile: 'default'

model-paths: ["models"]

models:
  remitano_dwh:
    staging:
      +materialized: view
    int:
      +materialized: view
    marts:
      +materialized: table
